services:
    app1:
        image: repo:app1
        hostname: app1
    app2:
        image: repo:app2
        hostname: app2
    proxy:
        image: repo:proxy
        ports:
        - "443:443"
        depends_on:
        - app1
        - app2